source: /docs
paths:
  uploads: docs
  static: docs
  collections: ''
  data: ''
  layouts:
collections_config:
  docs:
    path: docs
    output: true
    url: '"/[full_slug]/"'
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_enabled_editors:
  - visual
  - content
  - data
_inputs: {}
_select_data: {}
_structures: {}
_editables:
  content:
    blockquote: true
    bold: true
    bulletedlist: true
    center:
    code: true
    copyformatting: true
    correct_orientation: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6
    height:
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify:
    left:
    link: true
    mime_type:
    numberedlist: true
    outdent: true
    paths:
      uploads:
      dam_uploads:
      dam_static:
    redo: true
    removeformat: true
    resize_style: contain
    right:
    snippet: true
    strike: true
    styles:
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
    width:
data_config: {}
timezone: Etc/UTC
