site_name: VUMC IM Residency Handbook
site_url: https://beauhilton.github.io/neovimbook
repo_url: https://github.com/beauhilton/neovimbook
edit_uri: edit/main/docs/
docs_dir: 'docs'
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
theme:
  name: material
  font: 
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - search.suggest
    - search.highlight
    - search.share
  favicon: images/vumc-favicon.png
  logo: images/vumc-favicon.png
  palette:
    - scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
# VUMC Colors (https://www.vanderbilt.edu/communications/brand/color.php)
# Gold: Hex: D8AB4C, Black: Hex: 000000, Blue: Hex: 006682, Red: Hex:  993D1B, Dark Gray: Hex:  333333 Green: Hex:  464E21
