name: build mkdocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin
      - run: |
          mv index.md docs/index.md
          cd docs
          for f in **/*.Rmd; do mv "$f" "${f%%.Rmd}".md; done
      - run: mkdocs gh-deploy --force
