name: build mkdocs # 
on:
  push:
    branches: # 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # 
      - run: |
          mv index.md docs/md/index.md
          cd docs/md
          for f in **/*.Rmd; do mv "$f" "${f%%.Rmd}".md; done
      - run: mkdocs gh-deploy --force
